# Generated by Django 4.2 on 2024-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('code', models.CharField(default=123, max_length=25)),
                ('personal_id', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('motor_type', models.CharField(max_length=10)),
            ],
        ),
    ]
