# Generated by Django 4.2 on 2024-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers_info',
            name='city',
            field=models.CharField(choices=[('TEH', 'Tehran'), ('MHD', 'Mshhad'), ('ESF', 'Esfahan'), ('Urmo', 'Urmia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='drivers_info',
            name='motor_type',
            field=models.CharField(choices=[('C50', 'C50'), ('HU', 'Hiunda'), ('H2', 'Hunda'), ('BM', 'Bmw'), ('KH', 'Kavir')], max_length=10),
        ),
    ]
