# Generated by Django 4.2 on 2024-02-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_of_allopeyk',
            name='code',
        ),
    ]
