# Generated by Django 4.2 on 2024-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_users_of_allopeyk_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_of_allopeyk',
            name='code',
            field=models.CharField(default=123, max_length=25),
        ),
        migrations.DeleteModel(
            name='personal_info',
        ),
    ]
