# Generated by Django 4.2 on 2024-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_users_of_allopeyk_code_delete_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('code', models.CharField(default=123, max_length=25)),
                ('personal_id', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
