# Generated by Django 4.2 on 2024-03-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_users_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_of_ALLOPEYK',
        ),
    ]
