# Generated by Django 4.2 on 2024-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_users_info_user_type_pyke_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
