# Generated by Django 4.2 on 2024-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_pyke_request_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyke_request',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=100),
        ),
    ]
