# Generated by Django 4.2 on 2024-04-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_pyke_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='code',
            field=models.CharField(default=123, max_length=3),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='personal_id',
            field=models.CharField(default=1234567890, max_length=10),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='user_type',
            field=models.CharField(choices=[('peyk', 'peyk'), ('person', 'person')], default='person', max_length=10),
        ),
    ]
