# Generated by Django 4.2 on 2024-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_otp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='code',
            field=models.CharField(default=123, max_length=3, unique=True),
        ),
    ]
