# Generated by Django 4.2 on 2024-03-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0002_alter_drivers_info_city_and_more'),
        ('User', '0007_users_info_user_type_pyke_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=15)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.drivers_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users_info')),
            ],
        ),
    ]
