# Generated by Django 4.2 on 2024-04-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_orders_info_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_info',
            old_name='user',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='orders_info',
            name='driver',
        ),
    ]
