# Generated by Django 4.2 on 2024-04-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_rename_user_orders_info_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_info',
            old_name='person',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='orders_info',
            name='price',
        ),
    ]
